services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=luxmedtask'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/luxmedtask
    ports:
      - '8080:8080'